#Database - MySQL database in docker container
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_p5
spring.datasource.username=myuser
spring.datasource.password=verysecret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql: true
spring.sql.init.mode=always