flowchart LR
    MOVIE[PELICULA]
    GENRE[GENERO]
    RELEASE_YEAR[ANIO_ESTRENO]
    ACTOR[ACTOR]

    MOVIE_GENRE{PERTENECE_A}
    MOVIE_YEAR{SE_ESTRENA_EN}
    MOVIE_ACTOR{PARTICIPA_EN}

    MOVIE ---|N| MOVIE_GENRE
    MOVIE_GENRE ---|M| GENRE

    MOVIE ---|N| MOVIE_YEAR
    MOVIE_YEAR ---|1| RELEASE_YEAR

    MOVIE ---|N| MOVIE_ACTOR
    MOVIE_ACTOR ---|M| ACTOR

    MOVIE_ID((id))
    MOVIE_TITLE((title))
    GENRE_ID((id))
    GENRE_NAME((name))
    RELEASE_YEAR_ID((id))
    RELEASE_YEAR_VALUE((year_value))
    ACTOR_ID((id))
    ACTOR_NAME((name))

    MOVIE --- MOVIE_ID
    MOVIE --- MOVIE_TITLE
    GENRE --- GENRE_ID
    GENRE --- GENRE_NAME
    RELEASE_YEAR --- RELEASE_YEAR_ID
    RELEASE_YEAR --- RELEASE_YEAR_VALUE
    ACTOR --- ACTOR_ID
    ACTOR --- ACTOR_NAME
